// Language: ?lang=xx, then a saved choice, then the browser language. Portuguese, English, Spanish.

const DICT = {
  pt: {
    htmlLang: 'pt-BR',
    locale: 'pt-BR',
    kicker: 'TRANSMISSÃO 001',
    sub: 'uma única tomada · sem cortes · através de mundos',
    init: 'inicializando…',
    downloading: 'baixando a natureza',
    ready: 'pronto',
    phones: '🎧 use fones',
    go: 'clique para ligar o drone',
    fsnote: 'abre em tela cheia · Esc para sair',
    fsTitle: 'Tela cheia (F)',
    autoTitle: 'Modo automático (botão do meio do mouse)',
    autoBadge: 'AUTOMÁTICO',
    fine: 'desktop · role o mouse para avançar (e voltar) · botão do meio do mouse: modo automático',
    swwarn: '⚠ A aceleração de hardware do seu navegador está desligada: a GPU não vai trabalhar e tudo vai travar.<br>Ative em <b>Configurações → Sistema → "Usar aceleração de hardware"</b> e reabra o navegador.',
    nogl: 'Seu navegador não liberou a GPU (WebGL 2).<br>Ative em Configurações → Sistema → "Usar aceleração de hardware", reabra o navegador e recarregue.',
    hint: 'role · ou clique com o botão do meio',
    mute: 'Som (M)',
    endKicker: 'FIM DA TRANSMISSÃO',
    report: 'relatório da sua GPU',
    particles: 'partículas simuladas',
    tris: 'triângulos desenhados',
    frames: 'quadros renderizados',
    onAir: 'no ar',
    zero: '0 modelos 3D · 0 texturas · 0 arquivos de áudio baixados<br>o site inteiro pesa menos que uma foto de celular (~200 KB)',
    claim: 'Cada árvore, cada animal, cada estrela e cada som desta experiência foi gerado por código, em tempo real, no seu computador. Nenhum servidor renderizou nada.',
    createdBy: 'criado por',
    with: 'construído em parceria com Claude',
    again: '↺ assistir de novo',
    megabrain: 'renderizado com todo o poder do MEGABRAIN · copy chief: ativado ✓',
    gpuPrefix: 'sua',
    gpuFallback: 'sua placa de vídeo',
    billion: 'bi',
    million: 'mi',
    steps: ['esculpindo o lobo', 'esculpindo o urso', 'esculpindo o cervo', 'esculpindo a baleia', 'plantando a floresta', 'abrindo o olho', 'acendendo as estrelas', 'escrevendo as runas', 'erguendo a cidade', 'girando o planeta', 'compilando shaders na sua GPU'],
    captions: [
      'TRANSMISSÃO 001 · SINAL ESTABELECIDO',
      'Dizem que a floresta lembra de quem passa por ela.',
      'Nem tudo que te observa daqui está vivo do mesmo jeito.',
      'Alguns chamados atravessam mundos.',
      'E alguns guardiões só aparecem uma vez.',
      'Não desvie o olhar.',
      'Todo olho guarda um universo.',
      'Os antigos desenharam animais no céu.',
      'Eles nunca foram desenhos.',
      'Até a luz se curva para voltar para casa.',
      'Do outro lado, magia é só física que ainda não foi escrita.',
      '…e física é só magia que alguém escreveu.',
      'De longe, tudo vira uma luz pequena.',
      'Você achou que estava observando.',
      'Eles sempre estiveram olhando para você.',
    ],
  },
  en: {
    htmlLang: 'en',
    locale: 'en-US',
    kicker: 'TRANSMISSION 001',
    sub: 'one take · no cuts · across worlds',
    init: 'initializing…',
    downloading: 'downloading nature',
    ready: 'ready',
    phones: '🎧 wear headphones',
    go: 'click to power up the drone',
    fsnote: 'opens in fullscreen · Esc to exit',
    fsTitle: 'Fullscreen (F)',
    autoTitle: 'Autoplay (middle mouse button)',
    autoBadge: 'AUTOPLAY',
    fine: 'desktop · scroll to move forward (and back) · middle mouse button: autoplay',
    swwarn: '⚠ Your browser\'s hardware acceleration is off: the GPU won\'t do the work and everything will stutter.<br>Turn it on in <b>Settings → System → "Use hardware acceleration"</b> and restart the browser.',
    nogl: 'Your browser did not give this page access to the GPU (WebGL 2).<br>Turn on Settings → System → "Use hardware acceleration", restart the browser and reload.',
    hint: 'scroll · or middle-click for autoplay',
    mute: 'Sound (M)',
    endKicker: 'END OF TRANSMISSION',
    report: 'your GPU report',
    particles: 'particles simulated',
    tris: 'triangles drawn',
    frames: 'frames rendered',
    onAir: 'on air',
    zero: '0 3D models · 0 textures · 0 audio files downloaded<br>the whole site weighs less than a phone photo (~200 KB)',
    claim: 'Every tree, every animal, every star and every sound in this experience was generated by code, in real time, on your computer. No server rendered anything.',
    createdBy: 'created by',
    with: 'built together with Claude',
    again: '↺ watch again',
    megabrain: 'rendered with the full power of MEGABRAIN · copy chief: activated ✓',
    gpuPrefix: 'your',
    gpuFallback: 'your graphics card',
    billion: 'B',
    million: 'M',
    steps: ['sculpting the wolf', 'sculpting the bear', 'sculpting the deer', 'sculpting the whale', 'planting the forest', 'opening the eye', 'lighting the stars', 'writing the runes', 'raising the city', 'spinning the planet', 'compiling shaders on your GPU'],
    captions: [
      'TRANSMISSION 001 · SIGNAL ESTABLISHED',
      'They say the forest remembers everyone who passes through it.',
      'Not everything watching you here is alive in the same way.',
      'Some calls cross between worlds.',
      'And some guardians only appear once.',
      'Don\'t look away.',
      'Every eye holds a universe.',
      'The ancients drew animals in the sky.',
      'They were never drawings.',
      'Even light bends to find its way home.',
      'On the other side, magic is just physics no one has written yet.',
      '…and physics is just magic someone wrote down.',
      'From far enough away, everything becomes a small light.',
      'You thought you were the one watching.',
      'They were always watching you.',
    ],
  },
  es: {
    htmlLang: 'es',
    locale: 'es-ES',
    kicker: 'TRANSMISIÓN 001',
    sub: 'una sola toma · sin cortes · a través de mundos',
    init: 'inicializando…',
    downloading: 'descargando la naturaleza',
    ready: 'listo',
    phones: '🎧 usa auriculares',
    go: 'haz clic para encender el dron',
    fsnote: 'se abre en pantalla completa · Esc para salir',
    fsTitle: 'Pantalla completa (F)',
    autoTitle: 'Modo automático (botón central del ratón)',
    autoBadge: 'AUTOMÁTICO',
    fine: 'escritorio · usa la rueda del ratón para avanzar (y retroceder) · botón central: modo automático',
    swwarn: '⚠ La aceleración por hardware de tu navegador está desactivada: la GPU no trabajará y todo se trabará.<br>Actívala en <b>Configuración → Sistema → "Usar aceleración por hardware"</b> y reinicia el navegador.',
    nogl: 'Tu navegador no le dio acceso a la GPU (WebGL 2).<br>Activa Configuración → Sistema → "Usar aceleración por hardware", reinicia el navegador y recarga.',
    hint: 'desliza · o clic central para modo automático',
    mute: 'Sonido (M)',
    endKicker: 'FIN DE LA TRANSMISIÓN',
    report: 'informe de tu GPU',
    particles: 'partículas simuladas',
    tris: 'triángulos dibujados',
    frames: 'fotogramas renderizados',
    onAir: 'en el aire',
    zero: '0 modelos 3D · 0 texturas · 0 archivos de audio descargados<br>todo el sitio pesa menos que una foto del celular (~200 KB)',
    claim: 'Cada árbol, cada animal, cada estrella y cada sonido de esta experiencia fue generado por código, en tiempo real, en tu computadora. Ningún servidor renderizó nada.',
    createdBy: 'creado por',
    with: 'construido junto con Claude',
    again: '↺ ver de nuevo',
    megabrain: 'renderizado con todo el poder del MEGABRAIN · copy chief: activado ✓',
    gpuPrefix: 'tu',
    gpuFallback: 'tu tarjeta gráfica',
    billion: 'mil M',
    million: 'M',
    steps: ['esculpiendo el lobo', 'esculpiendo el oso', 'esculpiendo el ciervo', 'esculpiendo la ballena', 'plantando el bosque', 'abriendo el ojo', 'encendiendo las estrellas', 'escribiendo las runas', 'levantando la ciudad', 'girando el planeta', 'compilando shaders en tu GPU'],
    captions: [
      'TRANSMISIÓN 001 · SEÑAL ESTABLECIDA',
      'Dicen que el bosque recuerda a todos los que pasan por él.',
      'No todo lo que te observa aquí está vivo de la misma forma.',
      'Algunos llamados atraviesan mundos.',
      'Y algunos guardianes aparecen una sola vez.',
      'No apartes la mirada.',
      'Todo ojo guarda un universo.',
      'Los antiguos dibujaron animales en el cielo.',
      'Nunca fueron dibujos.',
      'Hasta la luz se curva para volver a casa.',
      'Del otro lado, la magia es solo física que nadie ha escrito todavía.',
      '…y la física es solo magia que alguien escribió.',
      'De lejos, todo se vuelve una pequeña luz.',
      'Creíste que eras tú quien observaba.',
      'Ellos siempre te estuvieron mirando.',
    ],
  },
};

export const LANGS = ['pt', 'en', 'es'];

function detect() {
  const q = new URLSearchParams(location.search).get('lang');
  if (q && DICT[q]) return q;
  try {
    const saved = localStorage.getItem('onetake.lang');
    if (saved && DICT[saved]) return saved;
  } catch (e) { /* storage blocked: fall through */ }
  const prefs = navigator.languages && navigator.languages.length ? navigator.languages : [navigator.language || 'en'];
  for (const l of prefs) {
    const base = String(l).toLowerCase().slice(0, 2);
    if (DICT[base]) return base;
  }
  return 'en';
}

export let lang = detect();
export const t = (key) => DICT[lang][key];

// fill every [data-i18n] / [data-i18n-html] element on the page
export function applyStatic() {
  document.documentElement.lang = DICT[lang].htmlLang;
  document.querySelectorAll('[data-i18n]').forEach((el) => { el.textContent = t(el.dataset.i18n); });
  document.querySelectorAll('[data-i18n-html]').forEach((el) => { el.innerHTML = t(el.dataset.i18nHtml); });
  document.querySelectorAll('[data-i18n-title]').forEach((el) => { el.title = t(el.dataset.i18nTitle); });
  document.querySelectorAll('[data-lang]').forEach((el) => el.classList.toggle('on', el.dataset.lang === lang));
}

export function setLang(l) {
  if (!DICT[l]) return;
  lang = l;
  try { localStorage.setItem('onetake.lang', l); } catch (e) { /* ignore */ }
  applyStatic();
}
